//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkhausMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dauermieter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dauermieter()
        {
            this.Zahlung = new HashSet<Zahlung>();
        }
    
        public int DauermieterID { get; set; }
        public string Name { get; set; }
        public string Vorname { get; set; }
        public Nullable<int> Code { get; set; }
        public Nullable<int> ParkplatzID { get; set; }
        public Nullable<System.DateTime> Erstelldatum { get; set; }
    
        public virtual Parkplatz Parkplatz { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zahlung> Zahlung { get; set; }
    }
}
