//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkhausMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Freie_Plaetze_Pro_Stockwerk
    {
        public Nullable<int> AnzahlParkplätze { get; set; }
        public int StockwerkID { get; set; }
    }
}
