//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkhausMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ParkhausDBEntities : DbContext
    {
        public ParkhausDBEntities()
            : base("name=ParkhausDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Parkplatz> Parkplatz { get; set; }
        public virtual DbSet<Stockwerk> Stockwerk { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Ticket> Ticket { get; set; }
        public virtual DbSet<Freie_Parkplaetze> Freie_Parkplaetze { get; set; }
        public virtual DbSet<Freie_Plaetze_Pro_Stockwerk> Freie_Plaetze_Pro_Stockwerk { get; set; }
        public virtual DbSet<Dauermieter> Dauermieter { get; set; }
        public virtual DbSet<Zahlung> Zahlung { get; set; }
        public virtual DbSet<Parktarif> Parktarif { get; set; }
        public virtual DbSet<Protokollierung> Protokollierung { get; set; }
        public virtual DbSet<Umsatz_pro_Monat> Umsatz_pro_Monat { get; set; }
    }
}
