//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkhausMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stockwerk
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Stockwerk()
        {
            this.Parkplatz = new HashSet<Parkplatz>();
        }
    
        public int StockwerkID { get; set; }
        public string Bezeichung { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parkplatz> Parkplatz { get; set; }
    }
}
