//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkhausMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Umsatz
    {
        public int EDMXID { get; set; }
        public string Typ { get; set; }
        public Nullable<int> MonatNr { get; set; }
        public string Monat { get; set; }
        public Nullable<int> Jahr { get; set; }
        public Nullable<decimal> Preis { get; set; }
    }
}
